comics/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings
from gargoyle.decorators import switch_is_active

from comics.views import (
    ComicPostView,
    ComicPreviewView,
    ComicListView,
    PostView,
    PostPreviewView,
    TaggedComicView,
    ComicAddView,
    ComicEditView,
    ComicDeleteView,
    CharacterAddView,
    CharacterEditView,
    CharacterView,
    CharacterDeleteView,
    PostEditView,
    PostAddView,
    PostDeleteView,
    LiveComicView,
    TagListView,
    TagAddView,
    TagEditView,
)

from comics.api import (
    S3SignView,
    APIComicListView,
    APIComicDetailView,
    APIPanelListView,
    APIPanelDetailView,
    APITagListView,
    APITagDetailView,
)

apipatterns = patterns('',
    url(
        r'^list/$',
        APIComicListView.as_view(),
        name='apicomiclistview',
    ),
    url(
        r'^panel/list/$',
        APIPanelListView.as_view(),
        name='apipanellistview',
    ),
    url(
        r'^panel/(?P<pk>[0-9]+)/$',
        APIPanelDetailView.as_view(),
        name='apipaneldetailview',
    ),
    url(
        r'^tag/list/$',
        APITagListView.as_view(),
        name='apitaglistview',
    ),
    url(
        r'^tag/(?P<pk>[0-9]+)/$',
        APITagDetailView.as_view(),
        name='apitagdetailview',
    ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        APIComicDetailView.as_view(),
        name='apicomicdetailview',
    ),
)

comicpatterns = patterns('',
    url(r'^$', ComicPostView.as_view(), name='comichomeview'),
    url(r'^all/$', ComicListView.as_view(), name='comiclistview'),
    url(r'^add/$', ComicAddView.as_view(), name='comicaddview'),
    url(r'^sign_s3/',
        S3SignView.as_view(),
        name='s3signview',
    ),
    url(r'^tags/$',
        switch_is_active(settings.COMIC_TAGGING)(TagListView.as_view()),
        name='taglistview'
    ),
    url(
        r'^live/$',
        switch_is_active(settings.LIVE_COMIC_VIEW)(LiveComicView.as_view()),
        name='livecomicview',
    ),
    url(r'^(?P<id>\d+)/$', ComicPostView.as_view()),
    url(
        r'^(?P<slug>[\w-]+)/$',
        ComicPostView.as_view(),
        name='comicpostview'
    ),
    url(
        r'^(?P<id>\d+)/preview/$',
        ComicPreviewView.as_view(),
        name='comicpreviewview'
    ),
    url(r'^tag/(?P<id>\d+)/$',
        switch_is_active(settings.COMIC_TAGGING)(TaggedComicView.as_view()),
        name='tagview',
    ),
    url(r'^(?P<id>\d+)/edit/$',
        ComicEditView.as_view(),
        name='comiceditview',
    ),
    url(r'^(?P<id>\d+)/delete/$',
        ComicDeleteView.as_view(),
        name='comicdeleteview',
    ),
)

postpatterns = patterns('',
    url(r'^add/$', PostAddView.as_view(), name='postaddview'),
    url(
        r'^(?P<slug>[\w-]+)/$',
        PostView.as_view(),
        name='postview'
    ),
    url(
        r'^(?P<id>\d+)/preview/$',
        PostPreviewView.as_view(),
        name='postpreviewview'
    ),
    url(
        r'^(?P<id>\d+)/edit/$',
        PostEditView.as_view(),
        name="posteditview",
    ),
    url(
        r'^(?P<id>\d+)/delete/$',
        PostDeleteView.as_view(),
        name="postdeleteview",
    ),
)

characterpatterns = patterns('',
    url(r'^add/$', CharacterAddView.as_view(), name='characteraddview'),
    url(
        r'^(?P<id>\d+)/edit/$',
        CharacterEditView.as_view(),
        name='charactereditview',
    ),
    url(
        r'^(?P<id>\d+)/delete/$',
        CharacterDeleteView.as_view(),
        name='characterdeleteview',
    ),
    url(r'^(?P<id>\d+)/$', CharacterView.as_view(), name="characterview"),
)

tagpatterns = patterns('',
    url(r'add/$', TagAddView.as_view(), name='tagaddview'),
    url(
        r'^(?P<id>\d+)/edit/$',
        TagEditView.as_view(),
        name='tageditview',
    ),
)

nest/urls.py
import nexus

from django.conf.urls import patterns, include, url
from django.contrib import admin

from robots_txt.views import RobotsTextView

from allauth.account.views import (
    signup,
    login,
    logout,
)

from nest.views import HomeRedirectView

from comics.views import (
    StaticPageView,
    ShareView,
    CharacterListView,
)

from comics.urls import (
    comicpatterns,
    postpatterns,
    characterpatterns,
    tagpatterns,
)
from comics.urls import apipatterns as comicapi

from comics.feeds import LatestPostFeed

from pebbles.urls import (
    pagepatterns,
    pebblepatterns,
)
from pebbles.views import (
    DashboardView,
)

from profiles.urls import profilepatterns

from reader.urls import readerpatterns

from recommendations.urls import apipatterns as likeapi
from recommendations.views import RecommendationListView

admin.autodiscover()
nexus.autodiscover()

apipatterns = patterns('',
    url(r'^comic/', include(comicapi)),
    url(r'^likes/', include(likeapi)),
)

urlpatterns = patterns('',
    url(r'^robots.txt$', RobotsTextView.as_view()),
    url(r'^$', HomeRedirectView.as_view(), name='home'),
    url(r'^likes/$', RecommendationListView.as_view(), name='like-list'),
    url(r'^api/', include(apipatterns)),
    url(r'^comic/', include(comicpatterns)),
    url(r'^post/', include(postpatterns)),
    url(r'^tag/', include(tagpatterns)),
    url(r'^feed/$', LatestPostFeed(), name='postfeed'),
    url(r'^read/', include(readerpatterns)),
    url(r'^pebbles/$', DashboardView.as_view(), name='dashview'),
    url(r'^pebble/', include(pebblepatterns)),
    url(r'^about/$', StaticPageView.as_view(), {'template': 'about.html'}),
    url(r'^profile/', include(profilepatterns)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^nexus/', include(nexus.site.urls)),
    url(r'^share/$', ShareView.as_view()),
    url(r'^characters/$', CharacterListView.as_view(), name='characterlistview'),
    url(r'^character/', include(characterpatterns)),
    url(r'^signup/$', signup),
    url(r'^login/$', login),
    url(r'^logout/$', logout),
    url(r'^p/', include(pagepatterns)),
)

profiles/urls.py
from django.conf.urls import patterns, include, url

from profiles.views import ProfileView

profilepatterns = patterns('',
    url(
        r'^(?P<username>[\w-]+)/$',
        ProfileView.as_view(),
        name='publicprofileview',
    ),
    url(r'^$', ProfileView.as_view(), name='profileview'),
)

recommendations/urls.py
from django.conf.urls import patterns, url

from recommendations.api import (
    APIRecommendationListView,
    APIRecommendationDetailView,
)

apipatterns = patterns('',
    url(
        r'^list/$',
        APIRecommendationListView.as_view(),
        name='api-like-list-view',
    ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        APIRecommendationDetailView.as_view(),
        name='api-like-detail-view',
    ),
)

comics/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify

from pebbles.models import Pebble

class PublishedComicManager(models.Manager):
    def get_query_set(self):
        return super(PublishedComicManager, self).get_query_set().filter(
                is_live=True
            ).filter(
                published__lte=timezone.now
            )


class ComicManager(models.Manager):

    def get_comics_for_user(self, user):
        pebbles = Pebble.objects.get_pebbles_for_user(user)
        return self.filter(pebbles__in=pebbles)

class Comic(models.Model):
    title = models.CharField(max_length=140)
    image_url = models.URLField()
    image_url_large = models.URLField(blank=True)
    alt_text = models.CharField(max_length=200, blank=True) 
    published = models.DateTimeField(default=timezone.now, blank=True)
    is_live = models.BooleanField(default=False)
    transcript = models.TextField(blank=True)
    thumb = models.URLField(blank=True, null=True)
    tags = models.ManyToManyField('Tag', blank=True, db_constraint=False)
    post = models.ForeignKey(
        'Post',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        db_constraint=False,
    )
    characters = models.ManyToManyField(
        'Character',
        blank=True,
        null=True,
        db_constraint=False,
    )
    creator = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        db_constraint=False
    )
    pebbles = models.ManyToManyField(
        Pebble,
        blank=True,
        null=True,
        db_constraint=False,
    )

    objects = ComicManager()

    published_comics = PublishedComicManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def slug(self):
        if self.post:
            return self.post.slug
        return slugify(self.title)

    def writers(self):
        return Contributor.objects.filter(post=self.post, role=Contributor.WRITER)

    def artists(self):
        return Contributor.objects.filter(post=self.post, role=Contributor.ARTIST)

    def creators(self):
        return Contributor.objects.filter(post=self.post, role=Contributor.CREATOR)

    def get_comic_url(self):
        try:
            pebbles = self.pebbles.all()
            return "http://%s%s" % (
                pebbles[0].settings().primary_domain.url,
                reverse('comicpostview', args=(self.post.slug,)),
            )
        except ValueError:
            return None

    def is_published(self):
        if self.is_live and self.published < timezone.now():
            return True
        return False

    def panels(self):
        return Panel.objects.filter(comic=self)

    # def can_edit(self, user):
    #     if self.pebbles

class PublishedPanelManager(models.Manager):
    def get_query_set(self):
        return super(PublishedPanelManager, self).get_query_set().filter(
            comic__is_live=True,
            comic__published__gte=timezone.now,
        )

class PanelManager(models.Manager):
    def get_panels_for_user(self, user):
        comics = Comic.objects.get_comics_for_user(user)
        panels = []
        panels += [comic.panels() for comic in comics]
        return panels

class Panel(models.Model):
    comic = models.ForeignKey(
        'Comic',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    number = models.SmallIntegerField(blank=True, null=True)
    image = models.URLField(blank=True, null=True)

    objects = PanelManager()

    published_panels = PublishedPanelManager()

    def __str__(self):
        return "Panel on %s" % (self.comic.title)

    class Meta:
        order_with_respect_to = 'comic'


class PublishedPostManager(models.Manager):
    def get_query_set(self):
        return super(PublishedPostManager, self).get_query_set().filter(
                is_live=True
            ).filter(
                published__lte=timezone.now
            )


class Post(models.Model):
    title = models.CharField(max_length=140)
    post = models.TextField(blank=True)
    slug = models.SlugField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    published = models.DateTimeField(default=timezone.now)
    is_live = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag', blank=True, db_constraint=False)
    creator = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        db_constraint=False,
    )
    pebbles = models.ManyToManyField(
        Pebble,
        blank=True,
        null=True,
        db_constraint=False,
    )

    objects = models.Manager()

    published_posts = PublishedPostManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def comic(self):
        try: 
            comic = Comic.objects.filter(post=self)[0]
        except IndexError:
            comic = None
        return comic

    def get_url(self):
        pebbles = self.pebbles.all()
        if not pebbles:
            if not self.comic:
                return get_post_url()
        else:
            return "http://%s%s" % (
                pebbles[0].settings.primary_domain.url,
                reverse('comicpostview', args=(self.slug,)),
            )

    def get_post_url(self):
        pebbles = self.pebbles.all()
        if not pebbles:
            return None
        else:
            return "http://%s%s" % (
                pebbles[0].settings.primary_domain.url,
                reverse('postview', args=(self.slug,)),
            )

    def is_published(self):
        if self.is_live and self.published < timezone.now():
            return True
        return False


class Character(models.Model):
    name = models.CharField(max_length=140)
    description = models.TextField(blank=True)
    profile_pic_url = models.URLField(blank=True)
    pebbles = models.ManyToManyField(
        Pebble,
        blank=True,
        null=True,
        db_constraint=False,
    )

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class TagManager(models.Manager):

    def get_tags_for_user(self, user):
        pebbles = Pebble.objects.get_pebbles_for_user(user)
        return self.filter(pebbles__in=pebbles)


class Tag(models.Model):
    tag = models.CharField(max_length=140)
    description = models.TextField(blank=True)
    header_image = models.URLField(blank=True)
    is_story = models.BooleanField(default=False)
    previous_tag = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='prev',
    )
    next_tag = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='next'
    )
    pebbles = models.ManyToManyField(
        Pebble,
        blank=True,
        null=True,
        db_constraint=False,
    )

    objects = TagManager()

    def get_first_comic(self):
        try:
            return Comic.published_comics.filter(
                tags__in=[self],
            ).order_by('published')[0]
        except:
            return None

    def __str__(self):
        return self.tag

    def __unicode__(self):
        return self.tag


class Contributor(models.Model):
    ARTIST = 0
    WRITER = 1
    CREATOR = 2
    ROLE_CHOICES = (
        (ARTIST, 'Artist'),
        (WRITER, 'Writer'),
        (CREATOR, 'Creator'),
    )

    post = models.ForeignKey('Post')
    contributor = models.ForeignKey(User)
    role = models.IntegerField(choices=ROLE_CHOICES)

    def __str__(self):
        return "%s:%s:%s" % (
            self.contributor,
            self.ROLE_CHOICES[self.role][1],
            self.post.title,
        )

recommendations/models.py
from django.db import models
from comics.models import Post
from pebbles.models import Pebble

class Recommendation(models.Model):
    COMIC = 0
    VIDEO_GAME = 1
    TYPE_CHOICES = (
        (COMIC, 'Comic'),
        (VIDEO_GAME, 'Video Game'),
    )

    name = models.CharField(max_length=140)
    url = models.URLField()
    kind = models.IntegerField(choices=TYPE_CHOICES)
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    pebble = models.ForeignKey(
        Pebble,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s: %s" % (
            self.TYPE_CHOICES[self.kind][1],
            self.name,
        )

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404

from comics.models import (
    Comic,
    Post,
    Contributor
)


class ProfileView(DetailView):
    template_name="profile.html"
    model = User

    def dispatch(self, *args, **kwargs):
        if kwargs.get('username'):
            self.user = get_object_or_404(User, username=kwargs.get('username'))
        elif self.request.user:
            self.user = self.request.user
        else:
            raise Http404()
        return super(ProfileView, self).dispatch(*args, **kwargs)

    def get_object(self):
        return self.user

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        contributions = Contributor.objects.filter(contributor=self.user)

        comics = Comic.published_comics.filter(
            post__contributor__in=contributions
        ).order_by('-published')

        posts = Post.published_posts.filter(
            contributor__in=contributions
        ).exclude(
            id__in=comics.values_list('post')
        ).order_by('-published')

        context['display_user'] = self.user
        context['posts'] = posts
        context['comics'] = comics

        return context

templates/add_comic.html
{% extends "base.html" %}
{% load staticfiles %}
{% load gargoyle_tags %}

{% block title %}
    {{ block.super }}
    {% if is_editing %}
        Edit Comic
    {% else %}
        Add Comic
    {% endif %}
{% endblock %}

{% block extra_head %}
{{ form.media }}
{% endblock %}

{% block content %}
<form enctype="multipart/form-data" action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row">
        <div class="col-md-offset-1 col-md-3">
            {% if is_editing %}
            <h3>Edit Comic</h3>
            {% else %}
            <h3>Add Comic</h3>
            {% endif %}
        </div>
        <div class="form-group col-md-3">
            {{ form.pebble.errors }}
            <span class="label label-default"><label for="id_pebble">Post To</label></span>
            {{ form.pebble }}
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-offset-1 col-md-3">
            {{ form.title.errors }}
            <span class="label label-default"><label for="id_title">Title</label></span>
            {{ form.title }}
        </div>
        <div class="form-group col-md-3">
            {{ form.slug.errors }}
            <span class="label label-default"><label for="id_slug">Slug</label></span>
            {{ form.slug }}
        </div>
        <div class="form-group col-md-2">
            {{ form.published.errors }}
            <span class="label label-default"><label for="id_published">Published</label></span>
            {{ form.published }}
        </div>
        <div class="form-group col-md-2">
            {{ form.is_live.errors }}
            <span class="label label-default"><label for="id_is_live">Is Live?</label></span>
            {{ form.is_live }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-1 col-md-3">
            <input type="file" id="files" onchange="s3_upload();" value="Choose a file"/>
            <p id="status">Please select a file</p>
        </div>
        <div class="form-group col-md-3">
            {{ form.image_url.errors }}
            <span class="label label-default"><label for="id_image_url">Image Url</label></span>
            {{ form.image_url }}
        </div>
        <div class="form-group col-md-3">
            {{ form.alt_text.errors }}
            <span class="label label-default"><label for="id_alt_text">Alt Text</label></span>
            {{ form.alt_text }}
        </div>
    </div>
    <div class="row" id="preview">
        {% if form.initial.image_url %}
        <img class="comic img-responsive" src="{{ form.initial.image_url}}" />
        {% endif %}
    </div>
    <div class="row row-padded">
        <div class="form-group col-md-offset-2 col-md-8">
            {{ form.post.errors }}
            <p class="label label-default"><label for="id_post">Post</label></p>
            {{ form.post }}
        </div>
    </div>
    {% ifswitch comic_tagging %}
    <div class="row row-padded">
        <div class="form-group col-md-8 col-md-offset-2">
            {{ form.tags.errors }}
            <p class="label label-default"><label for="id_tags">Tags</label></p>
            {{ form.tags }}
        </div>
    </div>
    {% endifswitch %}
    {% if fb_token or tw_token %}
    <div class="row row-padded">
        <div class="col-md-offset-2 col-md-2">
            <div class="form-group">
                {{ form.post_to_social.errors }}
                <p class="label label-default"><label for="id_post_to_social">Post to Social Networks?</label></p>
                {{ form.post_to_social}}
            </div>
            <div class="form-group">
                {{ form.social_post_time.errors }}
                <span class="label label-default"><label for="id_social_post_time">Social Post Time</label></span>
                {{ form.social_post_time }}
            </div>
        </div>
        {% if fb_token %}
        <div class="form-group col-md-3">
            {{ form.facebook_post_message.errors }}
            <span class="label label-default"><label for="id_facebook_post_message">Facebook Post Message</label></span>
            {{ form.facebook_post_message }}
            <p id="facebook-count">Characters:</p>
        </div>
        {% endif %}
        {% if tw_token %}
        <div class="form-group col-md-3">
            {{ form.twitter_post_message.errors }}
            <span class="label label-default"><label for="id_twitter_post_message">Twitter Post Message</label></span>
            {{ form.twitter_post_message }}
            <p id="twitter-count">Characters Left: 120</p>
        </div>
        {% endif %}
    </div>
    {% endif %}
    <input class="btn btn-success col-md-offset-1" type="submit" value="Save" />
    {% if is_editing %}
    <a class="btn btn-primary" href="{% url 'comicpreviewview' comic_id %}">Preview</a>
    {% endif %}
</form>
{% endblock %}

{% block js_defer %}
<script type="text/javascript" src="{% static "sass/javascripts/add_comic.js" %}"></script>
<script type="text/javascript" src="{% static "sass/javascripts/lodash.min.js" %}"></script>
<script type="text/javascript" src="{% static "sass/javascripts/s3upload.js" %}"></script>
<script type="text/javascript">
    window.AddComic.init()
</script>
<script type="text/javascript">
function s3_upload(){
    var s3upload = new S3Upload({
        file_dom_selector: '#files',
        s3_sign_put_url: '/comic/sign_s3/',
        onProgress: function(percent, message) {
            $('#status').html('Upload progress: ' + percent + '%' + message);
        },
        onFinishS3Put: function(public_url) { 
            // $('#status').html('Upload completed. Uploaded to: '+ public_url);
            $("#id_image_url").val(public_url);
            $("#preview").html('<img class="comic img-responsive" src="'+public_url+'" />');
        },
        onError: function(status) {
            $('#status').html('Upload error: ' + status);
        }
    });
}
</script>
{% endblock %}

templates/add_pebble_page.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    {{ block.super }}
    {% if is_editing %}
        Edit Page
    {% else %}
        Add Page
    {% endif %}
{% endblock %}

{% block extra_head %}
{{ form.media }}
{% endblock %}

{% block content %}
<form enctype="multipart/form_data" action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row">
        <div class="col-md-offset-1 col-md-3">
            {% if is_editing %}
            <h2>Edit Page</h2>
            {% else %}
            <h2>Add Page</h2>
            {% endif %}
        </div>
        <div class="form-group col-md-3">
            {{ form.pebble.errors }}
            <span class="label label-default"><label for="id_pebble">Page for</label></span>
            {{ form.pebble }}
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-offset-1 col-md-3">
            {{ form.title.errors }}
            <span class="label label-default"><label for="id_title">Title</label></span>
            {{ form.title }}
        </div>
        <div class="form-group col-md-3">
            {{ form.slug.errors }}
            <span class="label label-default"><label for="id_slug">Slug</label></span>
            {{ form.slug }}
        </div>
        <div class="form-group col-md-2">
            {{ form.is_live.errors }}
            <span class="label label-default"><label for="id_is_live">Is Live?</label></span>
            {{ form.is_live }}
        </div>
    </div>
    <div class="row row-padded">
        <div class="form-group col-md-offset-1 col-md-8">
            {{ form.content.errors }}
            <p class="label label-default"><label for="id_content">Content</label></p>
            {{ form.content }}
        </div>
    </div>
    <input class="btn btn-success col-md-offset-1" type="submit" value="Save" />
</form>
{% endblock %}
</script>

templates/character_delete.html
{% extends "base.html" %}

{% block title %}{{ block.super }}Delete Character{% endblock %}

{% block content %}
<h2>Deleting "{{ character.name }}"</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row form-group">
        {{ form.really_delete.errors }}
        <label for="id_really_delete">Are you sure you want to delete?</label>
        {{ form.really_delete }}
    </div>
    <input class="btn btn-success" type="submit" value="Submit" />
</form>
{% endblock %}

templates/characterlist.html
{% extends "base.html" %}

{% block title %}{{ block.super }}Characters{% endblock %}

{% block content %}
<h2>{{ pebble_settings.site_title }} Characters</h2>
<div class="row">
    {% for character in characters %}
    <div class="col-md-6">
        {% include "character.html" %}
    </div>
    {% if forloop.counter|divisibleby:"2" %}
</div>
<div class="row">
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

templates/characterview.html
{% extends "base.html" %}

{% block title %}{{ block.super }}{{ character.name }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% include "character.html" %}
    </div>
</div>
{% endblock %}

templates/disqus.html
{% if disqus_identifier %}
<div id="disqus_thread"></div>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{% endif %}

templates/footer.html
<div class="row footer">
    {% if pebble_settings.copyright %}
    <p><small>{{ pebble_settings.copyright }}</small></p>
    {% else %}
    <p><small>Copyright 2014 Inkpebble</small></p>
    {% endif %}
    <p>
        <small>
        {% if pebble_settings.twitter_page %} 
        <a href="http://twitter.com/{{ pebble_settings.twitter_page }}">@{{ pebble_settings.twitter_page }}</a> |
        {% endif %}
        {% if pebble_settings.facebook_page %}
        <a href="https://www.facebook.com/{{ pebble_settings.facebook_page }}">Find us on Facebook</a>
        {% endif %}
        </small>
    </p>
</div>

templates/list.html
{% for comic in object_list %}
    <div class="row">
        <h2 class="col-md-offset-1">
            <a href="/comic/{{ comic.post.slug }}">{{ comic.title }}</a>
            <small>{{ comic.published | date:"DATE_FORMAT" }}</small>
        </h2>
        <a title="{{ comic.alt_text }}" href="/comic/{{ comic.post.slug }}">
            <img class="img-responsive comic" src="{{ comic.image_url }}" alt="{{ comic.alt_text }}"></img>
        </a>
    </div>
{% endfor %}

templates/messages.html
{% if last_read_comic %}
<div class="row">
    <div class="col-md-6 col-md-offset-3 alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <span>Looks like you're not where you left off. Go to your last read page?</span>
        <a href="/comic/{{ last_read_comic }}/" class="btn btn-info btn-sm">Yes please!</a>
    </div>
</div>
{% endif %}

templates/pebblepage.html
{% extends "base.html" %}

{% block title %}{{ block.super }}{{ page.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {{ page.content | safe }}
    </div>
</div>
{% endblock %}

templates/tag_list.html
{% extends "base.html" %}

{% block title %}{{ block.super }}"{{ tag.tag }}" Comics{% endblock %}

{% block content %}

<div class="row">
    <h2 class="col-md-offset-1">{{ tag.tag }}</h2>
</div>

{% include "list.html" %}

{% endblock %}

templates/tags.html
{% extends "base.html" %}

{% block title %}{{ block.super }}Tags{% endblock %}

{% block content %}

<div class="row">
    <h2 class="col-md-offset-1">Tags</h2>
</div>

{% for tag in object_list %}
    <div class="row">
        <h3 class="col-md-offset-1">
            <a href="/comic/tag/{{ tag.id }}">{{ tag.tag }}</a>
        </h3>
    </div>
{% endfor %}

{% endblock %}